# Welcome to the config file. Please read the README.md file found at the ymls folder.

bot-token: "MTIyNjIwNTc2NTIyNDg5MDQyOA.GHwHaA.OAMIbllNWfYAbL6oWEvqMF3YnwZCtHdQFdAgGg" # The bot token for your bot.
text-prefix: "b."            # The prefix for text commands. They can be found at the README file mentioned above.

# Stuff that will be shown on /about.
about:
  description: "Collect balls on Discord. Made for people without Docker or PC." # Edits the first line of /about.
  github-link: "https://github.com/wascertified/dockerless-dex"                  # Only change this if you have a fork, this is not required and can be skipped.
  discord-invite: "https://discord.gg/RSdcTAn7FG"                                # Change to your discord server.

# Stuff that will be used on commands.
collectibles-name: "ball"       # Don't add an "s" as the bot will already add the extra "s".
bot-name: "Ancientdex"      # The name of the dex.
players-group-cog-name: "balls" # No spaces, must be lowercase.

authorized-users:
  - acelery
  
# For having multiple, just make sure it matches this look:
#  - 1234567890
#  - 1234567890

### NOTES ON AUTHORIZED USERS:
# Only give to people you trust.
# It will also give the user the permission of using the kill command (which turns off the bot)
# With great power comes great responsability.

# Bot startup status configuration.
startup_status:
  activity_type: "watching"                # Options: playing, streaming, listening, watching
  activity_name: "ancientdex"          # Name of the activity.
  status: "online"                            # Options: online, idle, dnd, invisible
  stream_url: "youtube.com"  # Required if activity_type is streaming.
